CREATE TABLE
    T_SXP_SCHEDULE
    (
        JOBNAME VARCHAR2(30) NOT NULL,
        JOBCNNAME VARCHAR2(60) NOT NULL,
        SERVERID VARCHAR2(100) NOT NULL,
        CRON VARCHAR2(100),
        FIXEDDELAYSTRING VARCHAR2(15),
        FIXEDRATESTRING VARCHAR2(15),
        INITIALDELAYSTRING VARCHAR2(15),
        UPDATETIME TIMESTAMP(6),
        PRIMARY KEY (JOBNAME)
    );